const photoCards = [
  {
    title: 'Curiosity1',
    name: 'Front Hazard Avoidance Camera',
    date: 'May 1, 2015',
    img_src: '../assets/photos/1.jpg',
    id: 'a1',
  },
  {
    title: 'Curiosity2',
    name: 'Front Hazard Avoidance Camera',
    date: 'May 2, 2015',
    img_src: '../assets/photos/2.jpg',
    id: 'a2',
  },
  {
    title: 'Curiosity3',
    name: 'Front Hazard Avoidance Camera',
    date: 'May 3, 2015',
    img_src: '../assets/photos/3.jpg',
    id: 'a3',
  },
  {
    title: 'Curiosity4',
    name: 'Front Hazard Avoidance Camera',
    date: 'May 4, 2015',
    img_src: '../assets/photos/4.jpg',
    id: 'a4',
  },
  {
    title: 'Curiosity5',
    name: 'Front Hazard Avoidance Camera',
    date: 'May 5, 2015',
    img_src: '../assets/photos/5.jpg',
    id: 'a5',
  },
  {
    title: 'Curiosity6',
    name: 'Front Hazard Avoidance Camera',
    date: 'May 6, 2015',
    img_src: '../assets/photos/6.jpg',
    id: 'a6',
  },
  {
    title: 'Curiosity7',
    name: 'Front Hazard Avoidance Camera',
    date: 'May 7, 2015',
    img_src: '../assets/photos/7.jpg',
    id: 'a7',
  },
  {
    title: 'Curiosity8',
    name: 'Front Hazard Avoidance Camera',
    date: 'May 8, 2015',
    img_src: '../assets/photos/8.jpg',
    id: 'a8',
  },
  {
    title: 'Curiosity9',
    name: 'Front Hazard Avoidance Camera',
    date: 'May 9, 2015',
    img_src: '../assets/photos/9.jpg',
    id: 'a9',
  },
  {
    title: 'Curiosity10',
    name: 'Front Hazard Avoidance Camera',
    date: 'May 10, 2015',
    img_src: '../assets/photos/10.jpg',
    id: 'a10',
  },
  {
    title: 'Curiosity11',
    name: 'Front Hazard Avoidance Camera',
    date: 'May 11, 2015',
    img_src: '../assets/photos/11.jpg',
    id: 'a11',
  },
  {
    title: 'Curiosity12',
    name: 'Front Hazard Avoidance Camera',
    date: 'May 12, 2015',
    img_src: '../assets/photos/12.jpg',
    id: 'a12',
  },
  {
    title: 'Curiosity13',
    name: 'Front Hazard Avoidance Camera',
    date: 'May 13, 2015',
    img_src: '../assets/photos/13.jpg',
    id: 'a13',
  },
  {
    title: 'Curiosity14',
    name: 'Front Hazard Avoidance Camera',
    date: 'May 14, 2015',
    img_src: '../assets/photos/14.jpg',
    id: 'a14',
  },
  {
    title: 'Curiosity15',
    name: 'Front Hazard Avoidance Camera',
    date: 'May 15, 2015',
    img_src: '../assets/photos/15.jpg',
    id: 'a15',
  },
  {
    title: 'Curiosity16',
    name: 'Front Hazard Avoidance Camera',
    date: 'May 16, 2015',
    img_src: '../assets/photos/16.jpg',
    id: 'a16',
  },
  {
    title: 'Curiosity17',
    name: 'Front Hazard Avoidance Camera',
    date: 'May 317, 2015',
    img_src: '../assets/photos/17.jpg',
    id: 'a17',
  },
  {
    title: 'Curiosity18',
    name: 'Front Hazard Avoidance Camera',
    date: 'May 318, 2015',
    img_src: '../assets/photos/18.jpg',
    id: 'a18',
  },
  {
    title: 'Curiosity19',
    name: 'Front Hazard Avoidance Camera',
    date: 'May 19, 2015',
    img_src: '../assets/photos/19.jpg',
    id: 'a19',
  },
  {
    title: 'Curiosity20',
    name: 'Front Hazard Avoidance Camera',
    date: 'May 20, 2015',
    img_src: '../assets/photos/20.jpg',
    id: 'a20',
  },
];

export default photoCards;
