const photoCards = [
  {
    name: "Curiosity1",
    description: "Front Hazard Avoidance Camera",
    date: "May 1, 2015",
    photo: require("../assets/photos/1.jpg"),
    key: "a1",
  },
  {
    name: "Curiosity2",
    description: "Front Hazard Avoidance Camera",
    date: "May 2, 2015",
    photo: require("../assets/photos/2.jpg"),
    key: "a2",
  },
  {
    name: "Curiosity3",
    description: "Front Hazard Avoidance Camera",
    date: "May 3, 2015",
    photo: require("../assets/photos/3.jpg"),
    key: "a3",
  },
  {
    name: "Curiosity4",
    description: "Front Hazard Avoidance Camera",
    date: "May 4, 2015",
    photo: require("../assets/photos/4.jpg"),
    key: "a4",
  },
  {
    name: "Curiosity5",
    description: "Front Hazard Avoidance Camera",
    date: "May 5, 2015",
    photo: require("../assets/photos/5.jpg"),
    key: "a5",
  },
  {
    name: "Curiosity6",
    description: "Front Hazard Avoidance Camera",
    date: "May 6, 2015",
    photo: require("../assets/photos/6.jpg"),
    key: "a6",
  },
  {
    name: "Curiosity7",
    description: "Front Hazard Avoidance Camera",
    date: "May 7, 2015",
    photo: require("../assets/photos/7.jpg"),
    key: "a7",
  },
  {
    name: "Curiosity8",
    description: "Front Hazard Avoidance Camera",
    date: "May 8, 2015",
    photo: require("../assets/photos/8.jpg"),
    key: "a8",
  },
  {
    name: "Curiosity9",
    description: "Front Hazard Avoidance Camera",
    date: "May 9, 2015",
    photo: require("../assets/photos/9.jpg"),
    key: "a9",
  },
  {
    name: "Curiosity10",
    description: "Front Hazard Avoidance Camera",
    date: "May 10, 2015",
    photo: require("../assets/photos/10.jpg"),
    key: "a10",
  },
  {
    name: "Curiosity11",
    description: "Front Hazard Avoidance Camera",
    date: "May 11, 2015",
    photo: require("../assets/photos/11.jpg"),
    key: "a11",
  },
  {
    name: "Curiosity12",
    description: "Front Hazard Avoidance Camera",
    date: "May 12, 2015",
    photo: require("../assets/photos/12.jpg"),
    key: "a12",
  },
  {
    name: "Curiosity13",
    description: "Front Hazard Avoidance Camera",
    date: "May 13, 2015",
    photo: require("../assets/photos/13.jpg"),
    key: "a13",
  },
  {
    name: "Curiosity14",
    description: "Front Hazard Avoidance Camera",
    date: "May 14, 2015",
    photo: require("../assets/photos/14.jpg"),
    key: "a14",
  },
  {
    name: "Curiosity15",
    description: "Front Hazard Avoidance Camera",
    date: "May 15, 2015",
    photo: require("../assets/photos/15.jpg"),
    key: "a15",
  },
  {
    name: "Curiosity16",
    description: "Front Hazard Avoidance Camera",
    date: "May 16, 2015",
    photo: require("../assets/photos/16.jpg"),
    key: "a16",
  },
  {
    name: "Curiosity17",
    description: "Front Hazard Avoidance Camera",
    date: "May 317, 2015",
    photo: require("../assets/photos/17.jpg"),
    key: "a17",
  },
  {
    name: "Curiosity18",
    description: "Front Hazard Avoidance Camera",
    date: "May 318, 2015",
    photo: require("../assets/photos/18.jpg"),
    key: "a18",
  },
  {
    name: "Curiosity19",
    description: "Front Hazard Avoidance Camera",
    date: "May 19, 2015",
    photo: require("../assets/photos/19.jpg"),
    key: "a19",
  },
  {
    name: "Curiosity20",
    description: "Front Hazard Avoidance Camera",
    date: "May 20, 2015",
    photo: require("../assets/photos/20.jpg"),
    key: "a20",
  },
];

export default photoCards;
